/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weilerhaus_productKeys_utils_ProductKeyUtils */

#ifndef _Included_com_weilerhaus_productKeys_utils_ProductKeyUtils
#define _Included_com_weilerhaus_productKeys_utils_ProductKeyUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weilerhaus_productKeys_utils_ProductKeyUtils
 * Method:    buildHexStr
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weilerhaus_productKeys_utils_ProductKeyUtils_buildHexStr
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
