/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bss_inc_utils_ProductKeyUtils */

#ifndef _Included_com_bss_inc_utils_ProductKeyUtils
#define _Included_com_bss_inc_utils_ProductKeyUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bss_inc_utils_ProductKeyUtils
 * Method:    buildHexStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bss_inc_utils_ProductKeyUtils_buildHexStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
